import {test,expect} from '@playwright/test';
import * as XLSX from 'xlsx';
import {validateRequirements} from '../shared/brief';
import {detailedBrief,detailedExtraction} from './fixtures/brief';
test('confirm requirements, choose ten headcounts, price from sheet rows and clear stale proposals',async({page})=>{
 let actionCalls=0;
 await page.addInitScript(()=>{const original=File.prototype.arrayBuffer; (window as unknown as {sheetReads:number}).sheetReads=0; File.prototype.arrayBuffer=function(){(window as unknown as {sheetReads:number}).sheetReads++;return original.call(this);};});
 const r=validateRequirements(detailedExtraction(),detailedBrief);
 await page.route('**/api/action',route=>{actionCalls++;return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({status:'success',value:r})});});
 const heads=['Taj Hotel Expenses','Bar Tenders','Guests Transfer (Toyota Crysta)','Entertainment','Technicals','Decor','Licenses & Permissions','Graphic Design & Printables','Photo / Video','Other Costs'];
 const rows:unknown[][]=[['Sr No','Description','Qty','Days','Total','Rate','Cost'],[null,null,null,null,null,null,'W/0 GST','NW','W']];
 heads.forEach((name,i)=>{rows.push([i+1,name,null,null,null,null,1000,0,1000]);if(i===0)rows.push([null,'Oct 24 - Lunch',100,1,100,8,800,0,800],[null,'Oct 24 - Sangeet',100,1,100,2,200,0,200],[null,'Oct 25 - High Tea',100,1,100,5,500,0,500]);});
 rows.push([null,'Total',null,null,null,null,10000,0,10000]);
 const book=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(rows),'Overall WIP');
 await page.goto('/'); await page.getByLabel('Paste the brief').fill(detailedBrief); await page.getByRole('button',{name:'Read the brief',exact:true}).click();
 await page.getByLabel('Excel costing sheet').setInputFiles({name:'invented.xlsx',mimeType:'application/octet-stream',buffer:XLSX.write(book,{type:'buffer',bookType:'xlsx'})});
 const cost=page.getByRole('button',{name:'Cost it',exact:true});await expect(cost).toBeDisabled();
 await expect(page.getByLabel('Headcount driving Guests Transfer (Toyota Crysta)',{exact:true})).toHaveValue('Out-of-town guests: 75');
 await expect(page.getByLabel('Headcount driving Technicals',{exact:true})).toHaveValue('Dinner: 1000');
 await expect(page.getByLabel('Calculation for Decor',{exact:true})).toHaveValue('fixed');
 await expect(page.getByRole('button',{name:'Confirm all',exact:true})).toBeDisabled();
 await page.getByLabel('Event city',{exact:true}).fill('Jaipur');
 await expect(page.getByLabel('City',{exact:true})).toHaveValue('Jaipur');
 await page.getByRole('button',{name:'Confirm all',exact:true}).click();
 await expect(page.getByRole('region',{name:'Costed proposal',exact:true})).toContainText('midpoint');
 await expect(page.getByText('Raw proposal output',{exact:true})).toHaveCount(0);
 const proposal=page.getByRole('region',{name:'Costed proposal',exact:true});
 for(const head of heads)await expect(proposal.getByLabel(`Contingency % for ${head}`,{exact:true})).toHaveValue(head==='Guests Transfer (Toyota Crysta)'?'10':'0');
 const checks=proposal.getByRole('region',{name:'Check before you send',exact:true});
 await expect(checks).toBeVisible();
 expect(await checks.getByRole('heading',{level:4}).allTextContents()).toEqual(['Missing information','Uncertain costs','Assumptions and choices']);
 const toggle=checks.locator('details');
 await expect(toggle).not.toHaveAttribute('open','');
 const detail=toggle.getByText(/^Guests Transfer \(Toyota Crysta\) — Transfers use 75 out-of-town guests;/);
 await expect(detail).not.toBeVisible();
 await expect(page.getByLabel('Guests the past transfers covered',{exact:true})).toHaveValue('');
 await expect(checks.getByText(/^Guests Transfer \(Toyota Crysta\) — Guests the past transfers covered:/)).toBeVisible();
 await expect(proposal.getByRole('heading',{name:'Guests Transfer (Toyota Crysta) · To quote',exact:true})).toBeVisible();
 await expect(checks.getByText('Per-person heads use the dinner count of 1,000: Technicals.',{exact:true})).toBeVisible();
 await checks.getByText('Show all assumptions',{exact:true}).click();
 await expect(detail).toBeVisible();
 await checks.getByText('Show all assumptions',{exact:true}).click();
 await expect(detail).not.toBeVisible();
 await page.getByLabel('Guests the past transfers covered',{exact:true}).fill('60');
 await expect(proposal).toHaveCount(0);
 await cost.click();
 await expect(proposal.getByRole('heading',{name:'Guests Transfer (Toyota Crysta) · ₹1,237.5–₹1,512.5 · midpoint ₹1,375',exact:true})).toBeVisible();
 await expect(checks.getByText(/^Contingency 10%: transfer count and vehicle needs often change close to the date/)).toBeVisible();
 const contingency=proposal.getByLabel('Contingency % for Guests Transfer (Toyota Crysta)',{exact:true});
 const transfers=proposal.locator('.proposal-head').filter({has:page.getByRole('heading',{name:/^Guests Transfer/})});
 const originalTotal=await proposal.locator('.proposal-total').innerText();
 const reads=await page.evaluate(()=>(window as unknown as {sheetReads:number}).sheetReads);
 const calls=actionCalls;
 await contingency.fill('20');
 await expect(transfers.getByRole('heading')).toHaveText('Guests Transfer (Toyota Crysta) · ₹1,350–₹1,650 · midpoint ₹1,500');
 await expect(transfers.getByText('Edited by you, was ₹1,375',{exact:true})).toBeVisible();
 expect(await proposal.locator('.proposal-total').innerText()).not.toBe(originalTotal);
 await transfers.getByRole('button',{name:'Reset to sheet',exact:true}).click();
 await expect(contingency).toHaveValue('10');
 await expect(proposal.locator('.proposal-total')).toHaveText(originalTotal);
 await expect(transfers.getByText(/^Edited by you/)).toHaveCount(0);
 await transfers.getByLabel('Quantity for Guests Transfer (Toyota Crysta)',{exact:true}).fill('150');
 await expect(transfers.getByRole('heading')).toHaveText('Guests Transfer (Toyota Crysta) · ₹2,475–₹3,025 · midpoint ₹2,750');
 await transfers.getByLabel('Unit cost for Guests Transfer (Toyota Crysta)',{exact:true}).fill('20');
 await expect(transfers.getByRole('heading')).toHaveText('Guests Transfer (Toyota Crysta) · ₹2,970–₹3,630 · midpoint ₹3,300');
 await transfers.getByRole('button',{name:'Reset to sheet',exact:true}).click();
 await expect(proposal.locator('.proposal-total')).toHaveText(originalTotal);
 expect(actionCalls).toBe(calls);
 expect(await page.evaluate(()=>(window as unknown as {sheetReads:number}).sheetReads)).toBe(reads);
 await expect(page.getByLabel('Guests the past transfers covered',{exact:true})).toHaveValue('60');
 await expect(page.getByLabel('Event city',{exact:true})).toHaveValue('Jaipur');
 await contingency.fill('101');
 await expect(proposal.locator('.proposal-total')).toHaveText('Enter a valid contingency for every head to show the pre-GST total.');
 await expect(checks.getByText(/^Guests Transfer \(Toyota Crysta\) — Contingency %: missing or invalid/)).toBeVisible();
 await contingency.fill('0');
 await expect(proposal.getByRole('heading',{name:'Guests Transfer (Toyota Crysta) · ₹1,125–₹1,375 · midpoint ₹1,250',exact:true})).toBeVisible();
 await contingency.fill('10');
 await expect(checks.getByText(/^Guests Transfer \(Toyota Crysta\) — Guests the past transfers covered:/)).toHaveCount(0);
 await page.getByLabel('Guests the past transfers covered',{exact:true}).fill('');
 await expect(proposal).toHaveCount(0);
 await cost.click();
 await expect(proposal.getByRole('heading',{name:'Guests Transfer (Toyota Crysta) · To quote',exact:true})).toBeVisible();
 await expect(checks).toContainText('To quote; excluded from the total.');
 expect(await checks.evaluate(el=>Boolean(el.compareDocumentPosition(el.closest('[aria-label="Costed proposal"]')!.querySelector('.proposal-total')!) & Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true);
 for(const head of heads.slice(1)){await expect(proposal.getByRole('heading',{name:new RegExp(`^${head.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')} ·`)})).toHaveCount(1);}
 await expect(proposal.locator('.proposal-line > strong').filter({hasText:/^Decor ·/})).toHaveCount(0);
 await expect(proposal.getByText('Overall WIP · Decor · row 11',{exact:true})).toHaveCount(1);
 await page.getByLabel('City',{exact:true}).fill('Jaipur');
 await page.getByLabel('Function 2 guest count',{exact:true}).fill('999');
 for(const h of heads)await page.getByLabel(`Choose a function for ${h}`,{exact:true}).selectOption('Dinner: 1000');
 await page.getByLabel('I confirm the requirements and matching rows.').check(); await expect(cost).toBeEnabled();await cost.click();
 const raw=page.getByRole('region',{name:'Costed proposal',exact:true});await expect(raw).toContainText('Day 1 · High tea · ₹1,125–₹1,375 · midpoint ₹1,250');await expect(raw).toContainText('Overall WIP · Taj Hotel Expenses · row 4');await expect(raw).toContainText('Accommodation · rooms and nights · ₹25,20,000–₹30,80,000');await expect(raw).toContainText('Day 1 · After party · To quote');
 await page.getByLabel('Calculation for Decor',{exact:true}).selectOption('headcount'); await expect(raw).toHaveCount(0);await cost.click();await expect(raw).toBeVisible();
 await page.getByLabel('Use my reviewed brief’s rooms, room rate and nights. No further season increase on this quoted rate.').check(); await cost.click(); await expect(raw).toContainText('Client brief · rooms, room rate and nights · confirmed by project head');
 // Missing variance must ask instead of silently using the previous brief’s percentage.
 await page.getByLabel('Variance',{exact:true}).fill('');
 await page.getByLabel('I confirm the requirements and matching rows.').check();
 await expect(cost).toBeDisabled();
 await expect(page.getByLabel('Variance percentage to use')).toBeVisible();
 await page.getByLabel('Variance percentage to use').fill('101');await expect(cost).toBeDisabled();
 await page.getByLabel('Variance percentage to use').fill('5');await expect(cost).toBeEnabled();await cost.click();
 await expect(raw).toContainText('Project head choice · Variance: ±5%');
 await expect(raw).toContainText('Day 1 · High tea · ₹1,187.5–₹1,312.5 · midpoint ₹1,250');
 await page.getByLabel('Variance percentage to use').fill('0');await expect(raw).toHaveCount(0);await cost.click();
 await expect(raw).toContainText('Day 1 · High tea · ₹1,250–₹1,250 · midpoint ₹1,250');
 await page.setViewportSize({width:390,height:844});await page.getByRole('heading',{name:'Costed first-pass proposal'}).scrollIntoViewIfNeeded();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.reload();await expect(raw).toHaveCount(0);await expect(page.getByLabel('Paste the brief')).toHaveValue('');
});
