import {test,expect} from '@playwright/test';
import * as XLSX from 'xlsx';
import {validateRequirements} from '../shared/brief';
import {detailedBrief,detailedExtraction} from './fixtures/brief';

for (const eventStated of [true,false]) test(`review ${eventStated?'a stated event':'a missing event type'}, confirmed scope and current costs, then return without losing edits`,async({page})=>{
 const brief=eventStated?detailedBrief:detailedBrief.replace('Hi team – sharing the wedding brief 👇','Hi team – here are the guest counts 👇');
 let actionCalls=0;
 await page.addInitScript(()=>{
  const original=File.prototype.arrayBuffer;
  (window as unknown as {sheetReads:number}).sheetReads=0;
  File.prototype.arrayBuffer=function(){(window as unknown as {sheetReads:number}).sheetReads++;return original.call(this);};
 });
 const r=validateRequirements(detailedExtraction(),detailedBrief);
 await page.route('**/api/action',route=>{actionCalls++;return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({status:'success',value:r})});});
 const heads=['Taj Hotel Expenses','Bar Tenders','Guests Transfer (Toyota Crysta)','Entertainment','Technicals','Decor','Licenses & Permissions','Graphic Design & Printables','Photo / Video','Other Costs'];
 const rows:unknown[][]=[['Sr No','Description','Qty','Days','Total','Rate','Cost'],[null,null,null,null,null,null,'W/0 GST','NW','W']];
 heads.forEach((name,i)=>{rows.push([i+1,name,null,null,null,null,1000,0,1000]);if(i===0)rows.push([null,'Oct 24 - Lunch',100,1,100,8,800,0,800],[null,'Oct 24 - Sangeet',100,1,100,2,200,0,200],[null,'Oct 25 - High Tea',100,1,100,5,500,0,500]);});
 rows.push([null,'Total',null,null,null,null,10000,0,10000]);
 const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(rows),'Overall WIP');
 await page.goto('/');await page.getByLabel('Paste the brief').fill(brief);
 await page.getByRole('button',{name:'Read the brief',exact:true}).click();
 await page.getByLabel('Excel costing sheet').setInputFiles({name:'invented.xlsx',mimeType:'application/octet-stream',buffer:XLSX.write(book,{type:'buffer',bookType:'xlsx'})});
 await page.getByLabel('Event city',{exact:true}).fill('Jaipur');
 await page.getByRole('button',{name:'Confirm all',exact:true}).click();
 const proposal=page.getByRole('region',{name:'Costed proposal',exact:true});
 const review=page.getByRole('main',{name:'Proposal review',exact:true});
 const open=page.getByRole('button',{name:'Review proposal',exact:true});
 // A missing transfer basis and To quote costs remain visible in the review.
 await open.click();
 await expect(review.getByText(/^Guests Transfer.*Guests the past transfers covered: missing/)).toBeVisible();
 await expect(review.getByRole('row').filter({has:page.getByRole('rowheader',{name:'Guests Transfer (Toyota Crysta)',exact:true})})).toContainText('To quote');
 await review.getByRole('button',{name:'Back to edit',exact:true}).click();
 await expect(open).toBeFocused();
 await page.getByLabel('Guests the past transfers covered',{exact:true}).fill('60');
 await page.getByRole('button',{name:'Cost it',exact:true}).click();
 await proposal.getByLabel('Contingency % for Guests Transfer (Toyota Crysta)',{exact:true}).fill('20');
 const total=await proposal.locator('.proposal-total').innerText();
 await expect(proposal.getByRole('heading',{name:/^Food & beverage \(minimum guarantee\) ·/})).toBeVisible();
 await expect(proposal.getByRole('heading').filter({hasText:/Taj|Hotel/i})).toHaveCount(0);
 await expect(proposal.getByText(/^Guest rooms · ₹/)).toBeVisible();
 await expect(proposal.getByText('Overall WIP · Taj Hotel Expenses · row 4',{exact:true})).toHaveCount(2);
 for(const source of await proposal.getByText('Overall WIP · Taj Hotel Expenses · row 4',{exact:true}).all())await expect(source).toBeVisible();
 const headPrices=await proposal.locator('.proposal-head > h3').allTextContents();
 const checks=proposal.getByRole('region',{name:'Check before you send',exact:true});
 const lists=await checks.locator(':scope > ul').allTextContents();
 const reads=await page.evaluate(()=>(window as unknown as {sheetReads:number}).sheetReads), calls=actionCalls;
 const city=await page.getByLabel('City',{exact:true}).inputValue();
 const dates=await page.getByLabel('Dates',{exact:true}).inputValue();
 const functions=await page.locator('.function-grid').evaluateAll(rows=>rows.map(row=>Array.from(row.querySelectorAll('input')).map(input=>input.value)));
 await open.click();
 await expect(review.getByText(eventStated?'Event: Wedding · 2 days':'Event: Not stated in brief',{exact:true})).toBeVisible();
 await expect(review.getByRole('heading',{level:1})).toBeFocused();
 expect(await review.getByRole('heading',{level:2}).allTextContents()).toEqual(['Scope','Assumptions','Costs']);
 await expect(page.getByRole('main')).toHaveCount(1);
 await expect(page.getByLabel('Event city',{exact:true})).not.toBeVisible();
 await expect(review.getByText(`City: ${city}`,{exact:true})).toBeVisible();
 await expect(review.getByText(`Dates: ${dates}`,{exact:true})).toBeVisible();
 for(const [day,name,guests] of functions)await expect(review.getByText(`${day} · ${name} · Guests: ${guests}`,{exact:true})).toBeVisible();
 const assumptions=review.getByRole('region',{name:'Assumptions',exact:true});
 const expectedLists=eventStated?lists:[`Event type: Not stated in brief.${lists[0]}`,...lists.slice(1)];
 expect(await assumptions.locator(':scope > ul').allTextContents()).toEqual(expectedLists);
 await expect(assumptions.getByText('Event type: Not stated in brief.',{exact:true})).toHaveCount(eventStated?0:1);
 await expect(assumptions.locator('details')).not.toHaveAttribute('open','');
 const table=review.getByRole('table',{name:'Reviewed costs',exact:true});
 await expect(table.getByRole('row')).toHaveCount(11);
 for(const [i,originalHead] of heads.entries()){
  const head=originalHead==='Taj Hotel Expenses'?'Food & beverage (minimum guarantee)':originalHead;
  const row=table.getByRole('row').filter({has:page.getByRole('rowheader',{name:head,exact:i!==2})});
  await expect(row).toHaveCount(1);
  const figure=headPrices[i].slice(head.length+3).split(' · midpoint ');
  await expect(row).toContainText(figure[0]);await expect(row).toContainText(figure[1]);
 }
 await expect(table.getByRole('rowheader',{name:'Food & beverage (minimum guarantee)',exact:true})).toBeVisible();
 await expect(table.getByText('Guest rooms',{exact:true})).toBeVisible();
 await expect(table.getByRole('rowheader').filter({hasText:/Taj|Hotel/i})).toHaveCount(0);
 await expect(table.getByText('Overall WIP · Taj Hotel Expenses · row 4',{exact:true})).toBeVisible();
 const transfers=table.getByRole('row').filter({has:page.getByRole('rowheader',{name:/^Guests Transfer/})});
 await expect(transfers).toContainText('Edited by you');await expect(transfers).toContainText('20%');
 await expect(transfers).toContainText('Overall WIP · Guests Transfer (Toyota Crysta) · row 8');
 await expect(review.locator('.proposal-total')).toHaveText(total);
 await expect(review.locator('input,select,textarea')).toHaveCount(0);
 await expect(review.getByRole('button')).toHaveCount(1);
 expect(await review.innerText()).not.toMatch(/deliverables|timelines|export/i);
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await review.getByRole('button',{name:'Back to edit',exact:true}).click();
 await expect(proposal.getByLabel('Contingency % for Guests Transfer (Toyota Crysta)',{exact:true})).toHaveValue('20');
 await expect(proposal.locator('.proposal-total')).toHaveText(total);
 await expect(page.getByLabel('Guests the past transfers covered',{exact:true})).toHaveValue('60');
 await expect(page.getByLabel('Event city',{exact:true})).toHaveValue(city);
 expect(actionCalls).toBe(calls);
 expect(await page.evaluate(()=>(window as unknown as {sheetReads:number}).sheetReads)).toBe(reads);
});
