import {test,expect} from '@playwright/test';
import * as XLSX from 'xlsx';
import {briefFromForm} from '../shared/briefForm';
import {validateRequirements} from '../shared/brief';
import {detailedBrief,detailedExtraction} from './fixtures/brief';
test('form and equivalent pasted brief cost identically, download a blank form, and expose excluded lines',async({page})=>{
 const raw=detailedExtraction();raw.fields.city='Jaipur';
 const draft={eventType:'Wedding',dates:'Last week of Dec 2026 | 2 days',city:'Jaipur',functions:raw.functions,services:detailedBrief.split('Day 1')[0]+'\nScaling rules\n'+detailedBrief.split('Scaling rules 👇')[1]};
 const equivalent=briefFromForm(draft), requests:string[]=[];
 await page.route('**/api/action',route=>{const input=route.request().postDataJSON();if(input.path!=='brief:structure')return route.continue();requests.push(input.args[0].brief);return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({status:'success',value:validateRequirements(raw,input.args[0].brief)})});});
 const heads=['Taj Hotel Expenses','Bar Tenders','Guests Transfer (Toyota Crysta)','Entertainment','Technicals','Decor','Licenses & Permissions','Graphic Design & Printables','Photo / Video','Other Costs'];
 const rows:unknown[][]=[['Sr No','Description','Qty','Days','Total','Rate','Cost'],[null,null,null,null,null,null,'W/0 GST','NW','W']];
 heads.forEach((name,i)=>{rows.push([i+1,name,null,null,null,null,1000,0,1000]);if(i===0)rows.push([null,'Oct 24 - Lunch',100,1,100,8,800,0,800],[null,'Oct 24 - Sangeet',100,1,100,2,200,0,200],[null,'Oct 25 - High Tea',100,1,100,5,500,0,500]);});
 rows.push([null,'Total',null,null,null,null,10000,0,10000]);
 const book=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(rows),'Overall WIP');

 await page.goto('/');
 await expect(page.getByRole('tab',{name:'Paste client brief'})).toHaveAttribute('aria-selected','true');
 await page.getByRole('tab',{name:'Fill brief form',exact:true}).click();
 const form=page.getByRole('tabpanel',{name:'Fill brief form',exact:true});
 await form.getByLabel('Event type',{exact:true}).fill(draft.eventType);
 await form.getByLabel('Event dates',{exact:true}).fill(draft.dates);
 await form.getByLabel('City',{exact:true}).fill(draft.city);
 for(const [i,f] of draft.functions.entries()){
  if(i)await form.getByRole('button',{name:'Add function',exact:true}).click();
  await form.getByLabel(`Day / date – Function ${i+1}`,{exact:true}).fill(f.day);
  await form.getByLabel(`Function name – Function ${i+1}`,{exact:true}).fill(f.name);
  await form.getByLabel(`Guest count – Function ${i+1}`,{exact:true}).fill(f.guests);
 }
 await form.getByLabel('Services mentioned',{exact:true}).fill(draft.services);
 const downloadPromise=page.waitForEvent('download');
 await form.getByRole('button',{name:'Download blank brief form',exact:true}).click();
 const download=await downloadPromise;
 expect(download.suggestedFilename()).toBe('blank-client-brief.txt');
 const stream=await download.createReadStream();let blank='';for await(const part of stream!)blank+=part.toString();
 expect(blank).toContain('CLIENT BRIEF');expect(blank).not.toContain('Jaipur');
 await page.getByLabel('Excel costing sheet').setInputFiles({name:'invented.xlsx',mimeType:'application/octet-stream',buffer:XLSX.write(book,{type:'buffer',bookType:'xlsx'})});
 await page.getByRole('button',{name:'Read the brief',exact:true}).click();
 await page.getByLabel('Guests the past transfers covered',{exact:true}).fill('60');
 await page.getByRole('button',{name:'Confirm all',exact:true}).click();
 const proposal=page.getByRole('region',{name:'Costed proposal',exact:true});
 const total=await proposal.locator('.proposal-total').innerText(),headsBefore=await proposal.locator('.proposal-head').allTextContents();
 const excluded=await proposal.locator('.pricing-status').innerText();
 await expect(proposal.locator('.pricing-status p')).toHaveText('To quote: 2 lines not in this total');
 await expect(proposal.locator('.pricing-status li')).toHaveText(['Food & beverage — Day 1 · After party','Food & beverage — Day 2 · After party']);
 await expect(proposal.locator('.pricing-status p')).toHaveClass('amber');
 await proposal.getByRole('button',{name:'Review proposal',exact:true}).click();
 const review=page.getByRole('main',{name:'Proposal review',exact:true});
 expect(await review.locator('.pricing-status').innerText()).toBe(excluded);
 await review.getByRole('button',{name:'Back to edit',exact:true}).click();
 await page.getByRole('tab',{name:'Paste client brief',exact:true}).click();
 await page.getByLabel('Paste the brief',{exact:true}).fill(equivalent);
 await page.getByRole('button',{name:'Read the brief',exact:true}).click();
 await page.getByLabel('Guests the past transfers covered',{exact:true}).fill('60');
 await page.getByRole('button',{name:'Confirm all',exact:true}).click();
 await expect(proposal.locator('.proposal-total')).toHaveText(total);
 expect(await proposal.locator('.proposal-head').allTextContents()).toEqual(headsBefore);
 expect(requests).toEqual([equivalent,equivalent]);
 // Remove the unquoted afters functions, retaining all prices for the other functions.
 const pricedRaw=structuredClone(raw);pricedRaw.functions=pricedRaw.functions.filter(f=>f.name!=='After party');
 await page.unroute('**/api/action');
 await page.route('**/api/action',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({status:'success',value:validateRequirements(pricedRaw,equivalent)})}));
 await page.getByRole('button',{name:'Read the brief',exact:true}).click();
 await page.getByLabel('Guests the past transfers covered',{exact:true}).fill('60');
 await page.getByRole('button',{name:'Confirm all',exact:true}).click();
 await expect(proposal.locator('.pricing-status p')).toHaveText('All lines priced');
 await expect(proposal.locator('.pricing-status p')).toHaveClass('priced-status');
 await expect(proposal.locator('.pricing-status li')).toHaveCount(0);
 await proposal.getByRole('button',{name:'Review proposal',exact:true}).click();
 await expect(review.locator('.pricing-status p')).toHaveText('All lines priced');
 await expect(review.locator('.pricing-status p')).toHaveClass('priced-status');
 await review.getByRole('button',{name:'Back to edit',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
