import {test,expect} from '@playwright/test';
import * as XLSX from 'xlsx';
import {validateRequirements} from '../shared/brief';
import {detailedBrief,detailedExtraction} from './fixtures/brief';
test('anonymous costing, private save, sign out and sign back in preserves edits and total',async({page})=>{
 const r=validateRequirements(detailedExtraction(),detailedBrief);
 let reads=0;
 await page.route('**/api/action',route=>{if(route.request().postDataJSON().path!=='brief:structure')return route.continue();reads++;return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({status:'success',value:r})});});
 const heads=['Taj Hotel Expenses','Bar Tenders','Guests Transfer (Toyota Crysta)','Entertainment','Technicals','Decor','Licenses & Permissions','Graphic Design & Printables','Photo / Video','Other Costs'];
 const rows:unknown[][]=[['Sr No','Description','Qty','Days','Total','Rate','Cost'],[null,null,null,null,null,null,'W/0 GST','NW','W']];
 heads.forEach((name,i)=>{rows.push([i+1,name,null,null,null,null,1000,0,1000]);if(i===0)rows.push([null,'Oct 24 - Lunch',100,1,100,8,800,0,800],[null,'Oct 24 - Sangeet',100,1,100,2,200,0,200],[null,'Oct 25 - High Tea',100,1,100,5,500,0,500]);});
 rows.push([null,'Total',null,null,null,null,10000,0,10000]);
 const book=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(rows),'Overall WIP');
 await page.goto('/'); await page.getByLabel('Paste the brief').fill(detailedBrief); await page.getByRole('button',{name:'Read the brief',exact:true}).click();
 await page.getByLabel('Excel costing sheet').setInputFiles({name:'invented.xlsx',mimeType:'application/octet-stream',buffer:XLSX.write(book,{type:'buffer',bookType:'xlsx'})});

 await expect(page.getByLabel('Headcount driving Food & beverage',{exact:true})).toBeVisible();
 await expect(page.getByLabel(/Headcount driving Taj/)).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Sign in',exact:true})).toHaveCount(0);
 await page.getByLabel('Event city',{exact:true}).fill('Jaipur');
 await page.getByLabel('Guests the past transfers covered',{exact:true}).fill('60');
 await page.getByRole('button',{name:'Confirm all',exact:true}).click();
 const proposal=page.getByRole('region',{name:'Costed proposal',exact:true});
 await expect(proposal.locator('.proposal-total')).toContainText('midpoint');
 await expect(page.getByRole('button',{name:'Sign in',exact:true})).toHaveCount(0);
 await proposal.getByLabel('Contingency % for Guests Transfer (Toyota Crysta)',{exact:true}).fill('20');
 await proposal.getByLabel('Unit cost for Decor',{exact:true}).fill('1234');
 const total=await proposal.locator('.proposal-total').innerText();
 const before=await proposal.locator('.proposal-head').allTextContents();
 await proposal.getByRole('button',{name:'Save this costing',exact:true}).click();
 await expect(page.getByLabel('Email',{exact:true})).toBeFocused();
 await expect(page.getByLabel('Email',{exact:true})).toBeInViewport();
 await expect(page.getByRole('region',{name:'My costings',exact:true}).getByRole('heading',{name:'My costings',exact:true})).toBeInViewport();
 const panel=page.getByRole('region',{name:'My costings',exact:true});
 const checkLinkSpacing=async(name:string)=>{
  const toggle=await panel.getByRole('button',{name,exact:true}).boundingBox();
  const back=await panel.getByRole('button',{name:'Back to costing',exact:true}).boundingBox();
  expect(toggle).not.toBeNull();expect(back).not.toBeNull();
  expect(back!.y-(toggle!.y+toggle!.height)).toBeGreaterThanOrEqual(12);
 };
 await checkLinkSpacing('Create an account');
 await page.getByRole('button',{name:'Create an account',exact:true}).click();
 await checkLinkSpacing('Use an existing account');
 const email=`costing-${Date.now()}-${Math.random().toString(36).slice(2)}@example.test`;
 const password='Invented-test-password-2026!';
 await page.getByLabel('Email',{exact:true}).fill(email);
 await page.getByLabel('Password',{exact:true}).fill(password);
 await page.getByRole('button',{name:'Create account',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('Costing saved.',{timeout:30000});
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await expect(page.getByRole('button',{name:'Sign out',exact:true})).toHaveCount(0);
 await page.reload();
 await page.getByRole('button',{name:'My costings',exact:true}).click();
 await page.getByLabel('Email',{exact:true}).fill(email);
 await page.getByLabel('Password',{exact:true}).fill(password);
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(panel.locator('li > strong')).toHaveText('Wedding · Last week of Dec 2026 · Jaipur');
 await page.getByRole('button',{name:'Open costing',exact:true}).click();
 await expect(proposal.locator('.proposal-total')).toHaveText(total);
 expect(await proposal.locator('.proposal-head').allTextContents()).toEqual(before);
 await expect(page.getByLabel('Guests the past transfers covered',{exact:true})).toHaveValue('60');
 await expect(page.getByLabel('Event city',{exact:true})).toHaveValue('Jaipur');
 await expect(proposal.getByLabel('Contingency % for Guests Transfer (Toyota Crysta)',{exact:true})).toHaveValue('20');
 await expect(page.getByLabel('Headcount driving Food & beverage',{exact:true})).toBeVisible();
 await expect(page.getByLabel(/Headcount driving Taj/)).toHaveCount(0);
 expect(reads).toBe(1);
 const saveButton=proposal.getByRole('button',{name:'Save this costing',exact:true});
 await saveButton.evaluate(button=>{(button as HTMLButtonElement).click();(button as HTMLButtonElement).click();});
 await expect(saveButton).toBeDisabled();
 await expect(page.getByRole('status')).toHaveText('Costing saved.');
 await expect(saveButton).toBeEnabled();
 await page.getByRole('button',{name:'My costings',exact:true}).click();
 await expect(panel.locator('li')).toHaveCount(1);
 await panel.getByRole('button',{name:'Back to costing',exact:true}).click();
 await proposal.getByLabel('Unit cost for Decor',{exact:true}).fill('2000');
 const newerTotal=await proposal.locator('.proposal-total').innerText();
 await proposal.getByRole('button',{name:'Save this costing',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('Costing saved.');
 await page.getByRole('button',{name:'My costings',exact:true}).click();
 await expect(panel.locator('li')).toHaveCount(2);
 await expect(panel.locator('li').first().locator('p')).toHaveText(newerTotal);
 await expect(panel.locator('time').first()).toHaveText(/^Saved \d{1,2} [A-Z][a-z]{2}, \d{1,2}:\d{2} [AP]M$/);
 page.once('dialog',dialog=>{expect(dialog.message()).toBe('Delete this costing?');void dialog.dismiss();});
 await panel.getByRole('button',{name:'Delete',exact:true}).last().click();
 await expect(panel.locator('li')).toHaveCount(2);
 page.once('dialog',dialog=>{expect(dialog.message()).toBe('Delete this costing?');void dialog.accept();});
 await panel.getByRole('button',{name:'Delete',exact:true}).last().click();
 await expect(panel.locator('li')).toHaveCount(1);
 await expect(panel.locator('li p')).toHaveText(newerTotal);
 await page.reload();
 await page.getByRole('button',{name:'My costings',exact:true}).click();
 await expect(panel.locator('li')).toHaveCount(1);
 console.log('MY COSTINGS AFTER DELETE\n'+await panel.innerText()+'\nEND MY COSTINGS');
 await panel.getByRole('button',{name:'Open costing',exact:true}).click();
 await expect(proposal.locator('.proposal-total')).toHaveText(newerTotal);
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await expect(proposal).toHaveCount(0);
});
