import { test, expect } from '@playwright/test';
import { ConvexHttpClient } from 'convex/browser';
import { api } from '../convex/_generated/api';
import { readFileSync, mkdirSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { dayOffset } from '../shared/planning';

const devUrl=readFileSync('.env.local','utf8').match(/^CONVEX_URL=(.+)$/m)?.[1]?.trim();
const client=new ConvexHttpClient(process.env.TEST_CONVEX_URL||devUrl!);
const randomKey=()=>randomBytes(32).toString('hex');
const date=dayOffset(new Date().toISOString().slice(0,10),7);
const yesterday=dayOffset(new Date().toISOString().slice(0,10),-1);
mkdirSync('.impeccable/review',{recursive:true});

test('host creates a gathering, tracks costs and tasks, and receives a WhatsApp-linked RSVP',async({page,browser,baseURL})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'More good times. Less last-minute scrambling.'})).toBeVisible();
  await page.screenshot({path:'.impeccable/review/welcome-desktop.png',fullPage:true});
  await page.getByLabel('Name your get-together').fill('Browser check · Saturday at home');
  await page.getByLabel('Date',{exact:true}).fill(date);
  await page.getByLabel('Overall budget (₹)').fill('10000');
  await page.getByLabel('Where are we meeting?').fill('Test gathering, Sample home');
  await page.getByRole('button',{name:'Create my plan'}).click();
  await expect(page.getByRole('heading',{name:'Browser check · Saturday at home',exact:true})).toBeVisible();
  const hostKey=new URL(page.url()).hash.slice('#host='.length);
  expect(hostKey).toMatch(/^[a-f0-9]{64}$/);
  await page.getByRole('button',{name:'I’ve saved it'}).click();
  await page.getByRole('button',{name:'Edit Arrange the main meal',exact:true}).click();
  await page.getByLabel('Quantity',{exact:true}).fill('3');
  await page.getByLabel('Unit price (₹)').fill('125.50');
  await page.getByLabel('Actual spend (₹)').fill('400');
  await page.getByLabel('Due date',{exact:true}).fill(yesterday);
  await page.getByLabel('Swiggy or Zomato outlet link').fill('https://www.swiggy.com/restaurants/test-outlet');
  await page.getByLabel('Price last checked').fill(yesterday);
  await page.getByRole('button',{name:'Save task',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Edit task',exact:true})).toHaveCount(0);
  const checkbox=page.getByRole('checkbox',{name:'Complete Arrange the main meal',exact:true});
  await checkbox.check();
  await expect(checkbox).toBeChecked();
  await expect(page.locator('.task-row.completed')).toContainText('Done late');
  await page.reload();
  await expect(checkbox).toBeChecked();
  await page.getByRole('button',{name:'Budget',exact:true}).click();
  await expect(page.locator('.budget-summary')).toContainText('₹376.50');
  await expect(page.locator('.budget-summary')).toContainText('₹400');
  await expect(page.locator('.budget-summary')).toContainText('₹9,600');
  await page.getByRole('button',{name:'Guests & invites',exact:true}).click();
  const inviteUrl=await page.getByLabel('Guest invitation link').inputValue();
  const waHref=await page.getByRole('link',{name:'Share on WhatsApp'}).getAttribute('href');
  expect(waHref).toContain('https://wa.me/?text=');
  expect(decodeURIComponent(waHref!)).toContain(inviteUrl);
  expect(decodeURIComponent(waHref!)).not.toContain(hostKey);
  const guestContext=await browser.newContext({baseURL,viewport:{width:390,height:844}});
  const guest=await guestContext.newPage();
  await guest.goto(inviteUrl);
  await expect(guest.getByRole('heading',{name:'Will we see you there?'})).toBeVisible();
  await guest.getByLabel('Your name',{exact:true}).fill('Sample Guest');
  await guest.getByLabel('People in your party, including you').fill('2');
  await guest.getByLabel('A note for the host (optional)').fill('Vegetarian, please');
  await guest.getByRole('button',{name:'Send my RSVP'}).click();
  await expect(guest.getByRole('heading',{name:'You’re on the list!'})).toBeVisible();
  await expect(page.locator('.guest-row')).toContainText('Sample Guest');
  await expect(page.locator('.guest-summary')).toContainText('2 people coming');
  await page.getByRole('button',{name:'Edit reply',exact:true}).click();
  await page.getByLabel('People in your party, including you').fill('3');
  await page.getByRole('button',{name:'Save guest reply'}).click();
  await expect(page.locator('.guest-summary')).toContainText('3 people coming');
  await guest.getByRole('button',{name:'Change my reply'}).click();
  await expect(guest.getByLabel('People in your party, including you')).toHaveValue('3');
  await guest.getByLabel('Not coming',{exact:true}).check();
  await guest.getByRole('button',{name:'Send my RSVP'}).click();
  await expect(guest.getByRole('heading',{name:'Thanks for letting us know.'})).toBeVisible();
  await expect(page.locator('.guest-row')).toHaveCount(1);
  await expect(page.locator('.guest-summary')).toContainText('0 people coming');
  await guest.getByRole('button',{name:'Change my reply'}).click();
  await guest.getByLabel('I’m coming',{exact:true}).check();
  await guest.getByRole('button',{name:'Send my RSVP'}).click();
  await expect(page.locator('.guest-summary')).toContainText('3 people coming');
  await page.getByRole('button',{name:/^Checklist/}).click();
  await expect(page.getByRole('checkbox',{name:'Complete Arrange the main meal',exact:true})).toBeChecked();
  await page.screenshot({path:'.impeccable/review/desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.reload();
  await expect(page.getByRole('heading',{name:'Your checklist',exact:true})).toBeVisible();
  await page.evaluate(()=>document.fonts.ready);
  await page.screenshot({path:'.impeccable/review/mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await guest.reload();
  await expect(guest.getByRole('heading',{name:'You’re on the list!'})).toBeVisible();
  await guest.screenshot({path:'.impeccable/review/invitation-mobile.png',fullPage:true});
  const inviteKey=new URL(inviteUrl).pathname.split('/').pop()!;
  expect(await client.query(api.events.get,{hostKey:inviteKey})).toBeNull();
  const publicEvent=await client.query(api.events.invitation,{inviteKey});
  expect(Object.keys(publicEvent).sort()).toEqual(['date','location','message','time','title']);
  expect(errors).toEqual([]);
  await guestContext.close();
});

test('host keys cannot edit another plan and invalid prices cannot be saved',async()=>{
  const hostKey=randomKey(),inviteKey=randomKey(),otherHost=randomKey();
  const values={title:'Browser check · permission test',date,time:'19:00',location:'',guests:8,budgetCents:100000,message:''};
  await client.mutation(api.events.create,{...values,hostKey,inviteKey});
  await client.mutation(api.events.create,{...values,hostKey:otherHost,inviteKey:randomKey()});
  const plan=await client.query(api.events.get,{hostKey});
  const task=plan.tasks[0];
  await expect(client.mutation(api.events.setDone,{hostKey:otherHost,taskId:task._id,done:true})).rejects.toThrow('Task not found in this plan');
  const taskValues={hostKey,taskId:task._id,category:task.category,title:task.title,quantity:1,unit:'servings',due:date};
  await expect(client.mutation(api.events.saveTask,{...taskValues,unitPriceCents:-100})).rejects.toThrow('Unit price');
  await expect(client.mutation(api.events.saveTask,{...taskValues,sourceUrl:'https://swiggy.com.evil.example/menu'})).rejects.toThrow('Use an https outlet link');
  expect((await client.query(api.events.get,{hostKey})).tasks[0].done).toBe(false);
});
