import {emptyFoodDay,printableBlankBrief,type FormLayoutDraft,type FormFunction} from '../shared/briefFormLayout';
export default function BriefFormLayout({draft,onChange,busy}:{draft:FormLayoutDraft;onChange:(draft:FormLayoutDraft)=>void;busy:boolean}) {
 const text=(key:'eventType'|'dates'|'city',label:string,placeholder:string)=><input aria-label={label} placeholder={placeholder} value={draft[key]} disabled={busy} maxLength={500} onChange={e=>onChange({...draft,[key]:e.target.value})}/>;
 const count=(label:string,value:string,unit:string,change:(value:string)=>void)=><div className="form-count"><input type="number" min="0" step="1" aria-label={label} value={value} disabled={busy} onChange={e=>change(e.target.value)}/><span>{unit}</span></div>;
 const daySection=(section:'rooms'|'transfers',title:string,unit:string)=><tbody aria-label={title}>{draft[section].map((value,i)=><tr key={i}><th scope="row">{i===0?title:''}</th><td>Day {i+1}</td><td>{count(`${title} – Day ${i+1}`,value,unit,next=>onChange({...draft,[section]:draft[section].map((old,index)=>index===i?next:old)}))}</td></tr>)}<tr><td></td><td><button className="add-detail" type="button" disabled={busy||draft[section].length>=30} onClick={()=>onChange({...draft,[section]:[...draft[section],'']})}>Add day</button></td><td></td></tr></tbody>;
 const changeFunction=(day:number,index:number,patch:Partial<FormFunction>)=>onChange({...draft,food:draft.food.map((rows,d)=>d===day?rows.map((row,i)=>i===index?{...row,...patch}:row):rows)});
 return <div role="tabpanel" id="form-brief-panel" aria-labelledby="form-brief-tab">
  <table className="brief-form-layout" aria-label="Client brief form"><colgroup><col/><col/><col/></colgroup><thead><tr><th>Section</th><th>Row</th><th>Your details</th></tr></thead>
   <tbody><tr><th scope="row">Event type</th><td></td><td>{text('eventType','Event type','Title')}</td></tr><tr><th scope="row">Event dates</th><td></td><td>{text('dates','Event dates','Mention days count only if dates unconfirmed')}</td></tr><tr><th scope="row">City</th><td></td><td>{text('city','City','Leave blank if unconfirmed')}</td></tr></tbody>
   {daySection('rooms','Guest Rooms','rooms')}{daySection('transfers','Guest Transfers','pax')}
   {draft.food.map((rows,day)=><tbody key={day} aria-label={`Food & Beverage – Day ${day+1}`}>{rows.map((row,index)=><tr key={index}><th scope="row">{day===0&&index===0?'Food & Beverage':''}</th><td>Day {day+1} - {row.custom?'Other function':row.name}</td><td>{row.custom&&<input aria-label={`Function name – Day ${day+1}, function ${index+1}`} placeholder="Function name" value={row.name} disabled={busy} maxLength={500} onChange={e=>changeFunction(day,index,{name:e.target.value})}/>} {count(`Day ${day+1} - ${row.custom?`Function ${index+1}`:row.name}`,row.guests,'pax',value=>changeFunction(day,index,{guests:value}))}</td></tr>)}<tr><td></td><td><button className="add-detail" type="button" disabled={busy||draft.food.flat().length>=30} onClick={()=>onChange({...draft,food:draft.food.map((old,index)=>index===day?[...old,{name:'',guests:'',custom:true}]:old)})}>Add function</button></td><td></td></tr></tbody>)}
   <tbody><tr><td></td><td><button className="add-detail" type="button" aria-label="Add day for Food & Beverage" disabled={busy||draft.food.flat().length+4>30} onClick={()=>onChange({...draft,food:[...draft.food,emptyFoodDay()]})}>Add day</button></td><td></td></tr></tbody>
   <tbody aria-label="Services Mentioned">{draft.services.map((service,index)=><tr key={index}><th scope="row">{index===0?'Services Mentioned':''}</th><td>{service.custom?'Additional service':service.name}</td><td>{service.custom&&<input aria-label={`Service name ${index+1}`} placeholder="Service name" disabled={busy} maxLength={500} value={service.name} onChange={e=>onChange({...draft,services:draft.services.map((row,i)=>i===index?{...row,name:e.target.value}:row)})}/>}<div className="service-note-input"><textarea aria-label={service.custom?`Service instructions ${index+1}`:service.name} placeholder="Please add quoted rates / special instructions" rows={2} maxLength={1500} value={service.note} disabled={busy} onChange={e=>onChange({...draft,services:draft.services.map((row,i)=>i===index?{...row,note:e.target.value}:row)})}/><small>Leave blank if none</small></div></td></tr>)}<tr><td></td><td><button className="add-detail" type="button" disabled={busy||draft.services.length>=30} onClick={()=>onChange({...draft,services:[...draft.services,{name:'',note:'',custom:true}]})}>Add service</button></td><td></td></tr></tbody>
  </table><button className="add-detail" type="button" onClick={()=>{const url=URL.createObjectURL(new Blob([printableBlankBrief],{type:'text/html;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='blank-client-brief.html';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Download blank brief form</button>
 </div>;
}
